import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Image from "next/image"
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className='max-w-6xl mx-auto h-28 flex justify-center md:justify-start items-center gap-4'><span><Image src="/images/veggie-carbonara.jpg" width="50" height="50" alt='logo' className='rounded-full'/></span><h1 className=' text-4xl font-bold'>Meraj's Recipes</h1></nav>
        {children}</body>
    </html>
  )
}
